---
title: "Methods Day"
author: "Leonard Blaschek"
date: '2022-08-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(showtext)
library(tidyverse)
library(ggtext)
library(gganimate)

#### import IBMPlexSans ####
font_add(
  "IBMPlexSans",
  regular = "/OFL_fonts/IBMPlexSans-Light.otf",
  italic = "/OFL_fonts/IBMPlexSans-LightItalic.otf",
  bold = "/OFL_fonts/IBMPlexSans-SemiBold.otf",
  bolditalic = "/OFL_fonts/IBMPlexSans-SemiBoldItalic.otf"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 8,
                      base_family = "IBMPlexSans") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_markdown(hjust = 0,
                                    size = 8),
      # axis.ticks = element_line(
      #   size = 0.25,
      #   lineend = "square",
      #   color = "black"
      # ),
      axis.title.y = element_markdown(size = 8),
      axis.title.x = element_markdown(size = 8),
      axis.ticks = element_blank(),
      axis.text.x = element_markdown(
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1),
        size = 8
      ),
      axis.text.y = element_markdown(
        colour = "black",
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1),
        size = 8
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      # panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "bottom",
      legend.text = element_text(size = rel(0.8)),
      legend.key.height = unit(4, "mm"),
      complete = TRUE
    )
}

pal_dawn <- c(
  "#434c52ff",
  "#46636fff",
  "#6088a0ff",
  "#ab6c82ff",
  "#d8737fff",
  "#eaa05fff",
  "#ffd175ff"
)

# convenience figure size functions
ggtext_size <- 8 / (14 / 5)
cm_size <- function(x) x / 2.54
twocol <- 18 / 2.54
onehalfcol <- 14 / 2.54
onecol <- 9 / 2.54
```

## Load data

```{r}
michels_data <- read_csv("/home/leonard/Dropbox/postdoc/group_meetings/2022-09-01_method-day/michels2020_averages.csv") %>% 
  mutate(sample = ordered(sample, levels = rev(unique(michels_data$sample))))
```

## Plot data

```{r}
michels_plot <-
  ggplot(michels_data,
         aes(x = region,
             y = tau)) +
  geom_segment(
    aes(
    colour = sample,
    x = region,
    xend = region,
    y = 0,
    yend = tau),
    size = 2,
    lineend = 'round') +
  geom_point(aes(fill = sample),
             shape = 21,
             stroke = 0.2,
             size = 4) +
  coord_flip() +
  labs(y = '<i>T</i> [ns]') +
  scale_colour_manual(values = pal_dawn, aesthetics = c('colour', 'fill')) +
  theme_leo() +
  theme(legend.position = 'none',
        axis.title.y = element_blank(),
        panel.grid.major.x = element_line()) +
  facet_wrap(~ sample, 
             ncol = 1,
             scales = "free_y")

pdf('michels_plot.pdf', height = onecol, width = onecol)
michels_plot
dev.off()
```

## Animation

```{r}
michels_plot <-
  ggplot(michels_data,
         aes(x = region,
             y = tau)) +
  # geom_segment(
  #   aes(
  #   colour = sample,
  #   x = region,
  #   xend = region,
  #   y = 0,
  #   yend = tau),
  #   size = 2,
  #   lineend = 'round') +
  geom_col(aes(fill = sample),
           size = 0.15) +
  geom_point(aes(fill = sample),
             shape = 21,
             stroke = 0.2,
             size = 4) +
  coord_flip() +
  labs(y = '<i>T</i> [ns]') +
  scale_colour_manual(values = pal_dawn, aesthetics = c('colour', 'fill')) +
  theme_leo() +
  theme(legend.position = 'none',
        axis.title.y = element_blank()) +
  facet_wrap(~ sample, 
             ncol = 1,
             scales = "free_y") +
  transition_states(sample) +
  enter_grow() +
  shadow_mark()
  

# pdf('michels_plot.pdf', height = onehalfcol, width = onecol)
michels_plot
# dev.off()

anim_save('tau.gif', height = onehalfcol, width = onecol, units = "in", res = 300)
```


