---
title: "Cellulose synthesis"
author: "Leonard Blaschek"
date: '2022-09-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggtext)
library(ggrepel)
library(ggridges)
library(tidygraph)
library(ggraph)
library(patchwork)
library(showtext)
library(tukeygrps)

## import Helvetica ####
font_add(
  "Helvetica",
  regular = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Lt.otf",
  italic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-LtIt.otf",
  bold = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-Bd.otf",
  bolditalic = "/prop_fonts/01. Helvetica   [1957 - Max Miedinger]/HelveticaNeueLTStd-BdIt.otf"
)

## import Arial ####
font_add(
  "Arial",
  regular = "/TTF/Arial.TTF",
  italic = "/TTF/Ariali.TTF",
  bold = "/TTF/Arialbd.TTF",
  bolditalic = "/TTF/Arialbi.TTF"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 7,
                      base_family = "Arial") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_markdown(
        hjust = 0,
        # face = "italic"
      ),
      axis.ticks = element_line(
        size = 0.125,
        lineend = "square",
        color = "black"
      ),
      axis.text.x = element_markdown(
        size = 7,
        colour = "black",
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_markdown(
        colour = "black",
        size = 7,
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      axis.title = element_markdown(
        colour = "black",
        size = 7
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "none",
      legend.text = element_text(size = 6),
      legend.key.height = unit(4, "mm"),
      plot.title = element_markdown(
        size = 7,
        hjust = 0
      ),
      complete = TRUE
    )
}

pal_ostwald_disc <- c(
  "#275d95",
  "#e8c245",
  "#d25952"
)

# convenience figure size functions
ggtext_size <- 7 / (14 / 5)
cm_size <- function(x) x / 2.54
twocol <- 18 / 2.54
onehalfcol <- 14 / 2.54
onecol <- 9 / 2.54
```

# CSC velocities

## CSC velocity to cellulose content regression

### Load relative data

```{r}
velo_data <- read_tsv('/home/leonard/Dropbox/2022_molplant_review/velocity_cellulose.tsv') %>% 
  mutate(colour = case_when(str_detect(`mutated gene`, 'CESA') ~ 'CESA',
                               perturbation == 'WT' ~ 'WT',
                               TRUE ~ 'accessory protein'),
         gene_type = case_when(str_detect(`mutated gene`, 'CESA') ~ 'CESA',
                               TRUE ~ 'accessory protein'),
         face = case_when(`perturbation type` == 'mutation' ~ 'italic',
                          TRUE ~ 'plain'),
         CESA = case_when(gene_type =='CESA' ~ `mutated gene`,
                          TRUE ~ 'accessory protein')) %>% 
  distinct(perturbation, .keep_all = TRUE) %>% 
  filter(`perturbation type` != 'drug') %>% 
  filter(perturbation != "WT")
```

### Calulate regression

```{r}
lm_velo_cellu <- lm(`velocity [% of WT]` ~ `cellulose [% of WT]`,
   data = velo_data)

rsq <- round(summary(lm_velo_cellu)$adj.r.squared, digits = 2)
```


### Plot regression

```{r}
velo_plot <- ggplot(velo_data,
                    aes(x = `velocity [% of WT]`,
                        y = `cellulose [% of WT]`,
                        # colour = colour
                        )) +
  annotate("rect",
           colour = NA,
           fill = pal_ostwald_disc[c(1, 3)],
           xmin = c(-Inf, 95),
           xmax = c(95, Inf),
           ymin = c(95, -Inf),
           ymax = c(Inf, 95),
           alpha = 0.5
           ) +
  geom_point(aes(shape = CESA)) +
  geom_smooth(
    aes(
      # colour = gene_type,
      # linetype = gene_type
        ),
    method = 'lm',
    se = FALSE,
    size = 0.4,
    colour = "black",
    linetype = 2) +
  geom_label_repel(
    data = velo_data %>% filter(gene_type != 'CESA'),
    aes(
      label = `perturbation`,
      fontface = face),
    size = ggtext_size,
    family = "Arial",
    label.size = NA,
    label.r = unit(0, 'mm'),
    label.padding = unit(0.5, 'mm'),
    fill = rgb(1, 1, 1, 0.75)
    ) +
  annotate("richtext",
           label = c(
             paste0("R<sup>2</sup> = ", rsq, " <i>(n.s.)</i>"),
             "<i><b>reduced velocity, unchanged cellulose</b></i>",
             "<i><b>unchanged velocity, reduced cellulose</b></i>"
           ),
           family = "Arial",
           size = ggtext_size,
           label.size = NA,
           fill = NA,
           colour = c("black", "white", "white"),
           hjust = c(1, 0.5, 0.5),
           vjust = c(1, 1, 0),
           angle = c(0, 0, 90),
           y = c(125, 125, 62.5),
           x = c(125, 62.5, 125)) +
  scale_linetype(guide = 'none') +
  scale_shape(name = 'Mutated gene') +
  scale_y_continuous(limits = c(30, 125), 
                     expand = expansion(add = 0),
                     breaks = c(40, 60, 80, 100, 120)) +
  scale_x_continuous(limits = c(30, 125), 
                     expand = expansion(add = 0),
                     breaks = c(40, 60, 80, 100, 120)) +
  labs(y = "Cellulose content [% of WT]",
       x = "CSC velocity [% of WT]") +
  theme_leo() +
  theme(
    # legend.position = c(0.12, 0.85)
    legend.position = "bottom",
    legend.text = element_text(size = 7)
    ) +
  coord_fixed()

pdf("velocity_cellulose.pdf", height = onecol, width = onecol)
velo_plot
dev.off()
```

## Distribution of WT velocities

### Load absolute data

```{r}
velo_data_WT <- read_tsv('/home/leonard/Dropbox/2022_molplant_review/velocity_cellulose.tsv') %>% 
  filter(perturbation == 'WT') %>% 
  mutate(colour = case_when(str_detect(`mutated gene`, 'CESA') ~ 'CESA',
                               perturbation == 'WT' ~ 'WT',
                               TRUE ~ 'accessory protein'),
         gene_type = case_when(str_detect(`mutated gene`, 'CESA') ~ 'CESA',
                               TRUE ~ 'accessory protein'),
         face = case_when(`perturbation type` == 'mutation' ~ 'italic',
                          TRUE ~ 'plain'),
         CESA = case_when(gene_type =='CESA' ~ `mutated gene`,
                          TRUE ~ 'accessory protein')) %>% 
  rename("label" = `tagged gene`,
         "velocity" = `velocity [nm/min]`)
```

### Plot WT velocity distribution

```{r}
letters <- letter_groups(
  velo_data_WT,
  velocity,
  label,
  'kruskal',
  print_position = 'below',
  print_adjust = 1.5)

medians <- velo_data_WT %>% 
  group_by(label) %>% 
  summarise(median = round(median(velocity, na.rm = TRUE)), digits = 0)

velo_dist <- ggplot(
  velo_data_WT,
  aes(x = velocity)
) +
  stat_density_ridges(aes(
    y = label,
    fill = `CESA type`,
  ),
  jittered_points = TRUE, 
  position = position_raincloud(height = 0.1, ygap = 0.01),
  colour = "white",
  point_shape = 21,
  point_stroke = 0.1,
  point_size = 0.8,
  quantile_lines = TRUE,
  quantiles = 2,
  alpha = 1,
  size = 0.2,
  scale = 0.9
  ) +
  geom_text(data = medians,
            aes(x = median,
                y = label,
                label = median),
            family = "Arial",
            fontface = "bold",
            size = ggtext_size,
            colour = 'white',
            vjust = -0.1,
            hjust = -0.1) +
  annotate("richtext",
           label = c("&mdash; <i>no significant differences</i> &mdash;",
                     "late stages of<br>differentiation"),
           family = "Arial",
           size = ggtext_size,
           label.size = NA,
           fill = NA,
           angle = c(90, 0),
           y = c(2.5, 4.4),
           x = c(500, 100)) +
  annotate("curve",
           y = 4.4,
           x = 160,
           yend = 4.25,
           xend = 183,
           curvature = -0.3,
           arrow = arrow(length = unit(1, "mm"),
                         type = "closed"),
           size = 0.2) +
  scale_colour_manual(values = c(pal_ostwald_disc[c(1, 3)]), aesthetics = c("colour", "fill")) +
  labs(x = "Velocity at the PM [nm min<sup>–1</sup>]",
       y = "Labelled protein") +
  theme_leo() +
  theme(legend.position = c(0.16, 0.08),
        legend.title = element_blank(),
        legend.key.height = unit(1, 'mm'),
        legend.key.width = unit(4, 'mm'),
        axis.title.x = element_markdown(),
        axis.title.y = element_blank())

pdf("WT_velocities.pdf", width = onecol * 0.75, height = onecol)
velo_dist
dev.off()
```

## Combined figure

```{r}
pdf("Pedersen2022_figureS1.pdf", width = twocol, height = onecol * 1.3)
velo_plot + velo_dist +
  plot_layout(ncol = 2, widths = c(2,1.25)) &
  plot_annotation(tag_levels = "A") &
  theme(plot.tag = element_text(size = 10, face = "bold", family = "Arial"))
dev.off()

```


# Transcriptional network of SCW formation

## Load data

```{r}
network_data <- read_csv("/home/leonard/Dropbox/2022_molplant_review/transcription_network.csv") %>% 
  as_tbl_graph()
```

## Plot network

```{r}
network <- ggraph(network_data, layout = 'graphopt') +
  geom_edge_fan(aes(colour = effect),
                 arrow = arrow(length = unit(4, 'mm')), 
                 end_cap = rectangle(width = 15, height = 7, 'mm')) +
  geom_edge_loop(aes(colour = effect),
                 arrow = arrow(length = unit(4, 'mm')), 
                 end_cap = rectangle(width = 15, height = 7, 'mm')) +
  geom_node_label(aes(label = name),
                  family = "Arial",
                  size = ggtext_size) +
  theme_void()
  

pdf("expression_network.pdf")
network
dev.off()
```

# PTM table

## Load data

```{r}
full_table <- read_tsv("/home/leonard/Dropbox/2022_molplant_review/PTM_table.tsv")

wide_table <- full_table %>% 
  fill(Modification, Protein) %>% 
  group_by(Modification, Protein) %>% 
  mutate(row_ID = row_number()) %>% 
  unite("Protein_row", Protein, row_ID) %>% 
  filter(str_detect(Protein_row, "CES")) %>%
  filter(!(Modification %in% c("Nitrosylation", "Glycosylation", "Acetylation"))) %>% 
  pivot_wider(
    names_from = Modification, 
    values_from = c("Site", "Modified by", "Effect", "Reference"),
    names_glue = "{Modification}_{.value}"
    ) %>% 
  select(
    Protein_row,
    Acylation_Site,
    `Acylation_Modified by`,
    Acylation_Effect,
    Acylation_Reference,
    Phosphorylation_Site,
    `Phosphorylation_Modified by`,
    Phosphorylation_Effect,
    Phosphorylation_Reference,
    Ubiquitination_Site,
    `Ubiquitination_Modified by`,
    Ubiquitination_Effect,
    Ubiquitination_Reference,
  )

write_csv(wide_table, "/home/leonard/Dropbox/2022_molplant_review/PTM_table_wide.csv")
```






