---
title: "Sulis et al. (2023) re-analysis"
author: "Leonard Blaschek"
output: 
  pdf_document:
    latex_engine: lualatex
    fig_caption: yes
    fig_height: 6
    includes:
      in_header: rmd_temp.tex
sansfont: IBM Plex Sans
monofont: IBM Plex Mono
bibliography: /home/leonard/Documents/Bibliography/Zotero_lib.bib
csl: elife.csl
link-citations: true
linkcolor: KU
urlcolor: KU
citecolor: KU
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
library(ggthemes)
library(showtext)
library(scales)
library(lubridate)
library(tidyverse)
library(ggrepel)
library(ggtext)

options(knitr.kable.NA = '')

#### import IBMPlexSans ####
font_add(
  "IBMPlexSans",
  regular = "/OFL_fonts/IBMPlexSans-Light.otf",
  italic = "/OFL_fonts/IBMPlexSans-LightItalic.otf",
  bold = "/OFL_fonts/IBMPlexSans-SemiBold.otf",
  bolditalic = "/OFL_fonts/IBMPlexSans-SemiBoldItalic.otf"
)
font_add(
  "IBMPlexMono",
  regular = "/OFL_fonts/IBMPlexMono-Regular.otf",
  italic = "/OFL_fonts/IBMPlexMono-Italic.otf",
  bold = "/OFL_fonts/IBMPlexMono-SemiBold.otf",
  bolditalic = "/OFL_fonts/IBMPlexMono-SemiBoldItalic.otf"
)
showtext_auto()

#### generating plot theme ####
theme_leo <- function(base_size = 8,
                      base_family = "IBMPlexSans") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
#       axis.ticks = element_line(
#         linewidth = 0.25,
#         lineend = "square",
#         color = "black"
#       ),
      axis.ticks = element_blank(),
      axis.text.x = element_text(
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1),
        size = 8
      ),
      axis.text.y = element_text(
        colour = "black",
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1),
        size = 8
      ),
      axis.title = element_text(size = 8),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      # panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "bottom",
      legend.text = element_text(size = rel(0.8)),
      legend.key.height = unit(4, "mm"),
      complete = TRUE
    )
}

ggtext_size <- 8 / (14 / 5)
```

```{r}
volume_data <- read_tsv("/home/leonard/Dropbox/Reviewing/post publication review/2023_Sulis/volume.tsv")
height_data <- read_tsv("/home/leonard/Dropbox/Reviewing/post publication review/2023_Sulis/lignin.tsv")

data <- full_join(volume_data, height_data, by = "ID") |> 
  mutate(label = case_when(str_detect(ID, "I-18|J-25|H-4|K-6|G-27") ~ ID,
                           TRUE ~ NA))
```

```{r}
highlight_plot <- ggplot(data,
       aes(x = rel_CL,
           y = rel_vol)) +
  geom_hline(yintercept = 100, size = 0.2) +
  geom_vline(xintercept = 100, size = 0.2) +
  geom_point(
    aes(fill = !is.na(label)),
    colour = "white",
    shape = 21,
    size = 2,
    stroke = 0.1) +
  scale_fill_manual(
    values = c(rgb(0,0,0,0.15), "#e8c245"),
    name = "Highlighted in main figures") +
  labs(x = "C/L ratio [% of WT]",
       y = "Stem volume [% of WT]") +
  # geom_smooth(method = "lm") +
  geom_label_repel(
    aes(label = label),
    family = "IBMPlexSans",
    size = ggtext_size,
    label.size = NA,
    label.padding = unit(1, "mm"),
    fill = rgb(1,1,1,0.75),
    min.segment.length = 0.3,
    segment.size = 0.2
    ) +
  theme_leo()

pdf("/home/leonard/Dropbox/Reviewing/post publication review/2023_Sulis/sulis_plot.pdf", height = 3, width = 4)
highlight_plot
dev.off()
```


