---
title: "Map of Europe"
author: "Leonard Blaschek"
date: '2022-05-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
library(showtext)
library(gganimate)
library(scales)
library(lubridate)
library(tidyverse)
library(ggrepel)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

#### import IBMPlexSans ####
font_add(
  "IBMPlexSans",
  regular = "/OFL_fonts/IBMPlexSans-Light.otf",
  italic = "/OFL_fonts/IBMPlexSans-LightItalic.otf",
  bold = "/OFL_fonts/IBMPlexSans-SemiBold.otf",
  bolditalic = "/OFL_fonts/IBMPlexSans-SemiBoldItalic.otf"
)
font_add(
  "Futura",
  regular = "FuturaStd-Medium.otf",
  italic = "FuturaStd-MediumOblique.otf",
  bold = "FuturaStd-Bold.otf",
  bolditalic = "FuturaStd-BoldOblique.otf"
)
showtext_auto()
showtext_opts(dpi = 300)

#### generating plot theme ####
theme_leo <- function(base_size = 6,
                      base_family = "Futura") {
  theme_minimal(
    base_size = base_size,
    base_family = base_family
  ) %+replace%
    theme(
      strip.text = element_text(hjust = 0, face = "italic"),
      # axis.ticks = element_line(
      #   size = 0.25,
      #   lineend = "square",
      #   color = "black"
      # ),
      axis.ticks = element_blank(),
      axis.text.x = element_text(
        colour = "black", # flipped coords
        margin = margin(1, 1, 1, 1)
      ),
      axis.text.y = element_text(
        colour = "black",
        angle = 0,
        vjust = 0.5,
        hjust = 1,
        margin = margin(1, 1, 1, 1)
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      # panel.border = element_rect(fill = NA, color = "black", size = 0.25),
      panel.spacing = unit(1.5, "mm"),
      legend.position = "bottom",
      legend.text = element_text(size = rel(0.8)),
      legend.key.height = unit(4, "mm"),
      complete = TRUE
    )
}

ggtext_size <- 6 / (14 / 5)
```

# Path until now

## Load data

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf", continent = "europe")

POIs <- tribble(
  ~lat, ~lon, ~name, ~relevance,
  52.770490, 11.877250, "Rohrbeck", "grey50",
  52.52, 13.405, "Berlin", "grey50",
  54.083333, 13.383333, "Greifswald", "black",
  59.858056, 17.644722, "Uppsala", "black",
  59.329444, 18.068611, "Stockholm", "black",
  55.676111, 12.568333, "Copenhagen", "black",
  63.828333, 20.270556, "Umeå", "black"
)
```

## Plot map

```{r}
map <- ggplot() +
  geom_sf(
    data = world,
    colour = "white",
    fill = "#275d95",
    size = 0.5
  ) +
  coord_sf(xlim = c(-8, 28), ylim = c(50, 71), expand = FALSE) +
  geom_point(
    data = POIs,
    aes(
      x = lon,
      y = lat,
      fill = relevance
    ),
    colour = "black",
    shape = 21,
    size = 4,
    stroke = 1,
    inherit.aes = FALSE
  ) +
  geom_label(
    data = POIs[1, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    nudge_x = -1,
    hjust = 1,
    family = "Futura",
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  annotate("curve", # Rohrbeck -> Berlin
    colour = "#e8c245",
    size = 1.5,
    lineend = "butt",
    curvature = 0.4,
    x = 11.877250,
    y = 52.770490,
    xend = 13,
    yend = 52.52,
    arrow = arrow(
      type = "closed",
      length = unit(1.5, "mm")
    )
  ) +
  geom_label(
    data = POIs[2, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    nudge_x = 1,
    hjust = 0,
    family = "Futura",
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  annotate("curve", # Berlin -> Greifswald
    colour = "#e8c245",
    size = 1.5,
    lineend = "butt",
    curvature = 0.3,
    x = 13.405,
    y = 52.52,
    xend = 13.5,
    yend = 53.8,
    arrow = arrow(
      type = "closed",
      length = unit(1.5, "mm")
    )
  ) +
  geom_label(
    data = POIs[3, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    nudge_x = -1,
    hjust = 1,
    family = "Futura",
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  annotate("curve", # Greifswald -> Uppsala
    colour = "#e8c245",
    size = 1.5,
    lineend = "butt",
    curvature = -0.1,
    x = 13.383333,
    y = 54.083333,
    xend = 17.3,
    yend = 59.6,
    arrow = arrow(
      type = "closed",
      length = unit(1.5, "mm")
    )
  ) +
  geom_label(
    data = POIs[4, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    nudge_x = -1,
    hjust = 1,
    family = "Futura",
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  annotate("curve", # Uppsala -> Stockholm
    colour = "#e8c245",
    size = 1.5,
    lineend = "butt",
    curvature = -0.2,
    x = 17.644722,
    y = 59.858056,
    xend = 18.068611,
    yend = 59.4,
    arrow = arrow(
      type = "closed",
      length = unit(1.5, "mm")
    )
  ) +
  geom_label(
    data = POIs[5, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    nudge_x = 1,
    hjust = 0,
    family = "Futura",
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  annotate("curve", # Stockholm -> Copenhagen
    colour = "#e8c245",
    size = 1.5,
    lineend = "butt",
    curvature = -0.4,
    x = 18.068611,
    y = 59.329444,
    xend = 13.15,
    yend = 55.7,
    arrow = arrow(
      type = "closed",
      length = unit(1.5, "mm")
    )
  ) +
  geom_label(
    data = POIs[6, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    # face = 2,
    nudge_x = -1,
    hjust = 1,
    family = "Futura",
    # fontface = 2,
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  annotate("curve", # Copenhagen - Umeå
    colour = "#e8c245",
    size = 1.5,
    lineend = "butt",
    curvature = -0.7,
    x = 12.568333,
    y = 55.676111,
    xend = 20,
    yend = 63.828,
    arrow = arrow(
      type = "closed",
      length = unit(1.5, "mm")
    )
  ) +
  geom_label(
    data = POIs[7, ],
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    nudge_x = 1,
    hjust = 0,
    family = "Futura",
    fontface = 2,
    size = ggtext_size,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5),
    # fill = NA,
    colour = "black"
  ) +
  # geom_label_repel(
  #   data = POIs,
  #   aes(
  #     x = lon,
  #     y = lat,
  #     label = name,
  #     colour = relevance
  #   ),
  #   seed = 948,
  #   family = "Futura",
  #   size = ggtext_size,
  #   min.segment.length = 2,
  #   label.size = NA,
  #   label.r = (unit(0, "mm")),
  #   fill = rgb(1, 1, 1, 0.5),
  #   # fill = NA,
  #   colour = "black"
  # ) +
  scale_fill_manual(values = c("white", "grey50")) +
  theme_leo() +
  theme(
    panel.background = element_rect(fill = "white", colour = NA),
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank()
    # plot.background = element_rect(fill = "#fff9f5ff", colour = NA)
  ) +
  transition_layers(layer_order = c(1, 2, 3:15)) +
  enter_grow()

# pdf("europe.pdf", height = 5)
# map
# dev.off()

animate(
  map,
  units = "px",
  width = 618,
  height = 720,
  nframes = 200,
  fps = 25,
  renderer = gifski_renderer(loop = FALSE)
)

anim_save("europe.gif")
```

# Stockholm

## Load data

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf", continent = "europe")

POIs <- tribble(
  ~lat, ~lon, ~name, ~relevance,
  59.329444, 18.068611, "Stockholm", "black",
)
```

## Plot map

```{r}
map <- ggplot() +
  geom_sf(
    data = world,
    colour = "white",
    fill = "darkseagreen",
    size = 0.25
  ) +
  coord_sf(xlim = c(-11, 31), ylim = c(44, 71), expand = FALSE) +
  geom_point(
    data = POIs,
    aes(
      x = lon,
      y = lat,
      colour = relevance
    ),
    size = 2,
    inherit.aes = FALSE
  ) +
  geom_label_repel(
    data = POIs,
    aes(
      x = lon,
      y = lat,
      label = name,
      colour = relevance
    ),
    seed = 948,
    nudge_x = 3,
    family = "IBMPlexSans",
    size = ggtext_size,
    min.segment.length = 2,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5)
  ) +
  scale_colour_manual(values = c("black", "grey50")) +
  theme_leo() +
  theme(
    panel.background = element_rect(fill = "lightblue", colour = NA),
    legend.position = "none",
    plot.background = element_rect(fill = "#fff9f5ff", colour = NA)
  )

pdf("Stockholm.pdf", width = 5, height = 5.7)
map
dev.off()
```

# CPH--Freiburg

## Load data

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf", continent = "europe")

POIs <- tribble(
  ~lat, ~lon, ~name, ~relevance,
  55.676111, 12.568333, "Copenhagen", "black",
  47.995, 7.85, "Freiburg", "black"
)
```

## Plot map

```{r}
map <- ggplot() +
  geom_sf(
    data = world,
    colour = "white",
    fill = "darkseagreen",
    size = 0.25
  ) +
  coord_sf(xlim = c(-11, 31), ylim = c(44, 71), expand = FALSE) +
  geom_point(
    data = POIs,
    aes(
      x = lon,
      y = lat,
      colour = relevance
    ),
    size = 2,
    inherit.aes = FALSE
  ) +
  annotate("curve", # CPH <-> Freiburg
    colour = "#e8c245",
    size = 1,
    linetype = 1,
    lineend = "butt",
    curvature = 0.2,
    x = 12.1,
    y = 55.2,
    xend = 7.85,
    yend = 48.5,
    arrow = arrow(
      type = "closed",
      length = unit(2, "mm"),
      ends = "both"
    )
  ) +
  geom_label_repel(
    data = POIs,
    aes(
      x = lon,
      y = lat,
      label = name,
      colour = relevance
    ),
    seed = 948,
    nudge_x = 3,
    family = "IBMPlexSans",
    size = ggtext_size,
    min.segment.length = 2,
    label.size = NA,
    label.r = (unit(0, "mm")),
    fill = rgb(1, 1, 1, 0.5)
  ) +
  scale_colour_manual(values = c("black", "grey50")) +
  theme_leo() +
  theme(
    panel.background = element_rect(fill = "lightblue", colour = NA),
    legend.position = "none",
    plot.background = element_rect(fill = "#fff9f5ff", colour = NA)
  )

pdf("CPH-Freiburg.pdf", width = 5, height = 5.7)
map
dev.off()
```

# UPSC

## Load data

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf", continent = "europe")

POIs <- tribble(
  ~lat, ~lon, ~name, ~relevance,
  63.82489089420472, 20.263092634420218, "Umeå", "black",
)
```

## Plot map

```{r}
map <- ggplot() +
  geom_sf(
    data = world,
    colour = "white",
    fill = "darkgreen",
    size = 0.25
  ) +
  coord_sf(xlim = c(-13, 31), ylim = c(35, 75), expand = FALSE) +
  geom_point(
    data = POIs,
    aes(
      x = lon,
      y = lat,
    ),
    shape = 21,
    colour = "black",
    fill = "white",
    stroke = 1,
    size = 2,
    inherit.aes = FALSE
  ) +
  geom_text(
    data = POIs,
    aes(
      x = lon,
      y = lat,
      label = name
    ),
    size = 3,
    color = "white",
    nudge_x = -2.5,
    nudge_y = 1,
    family = "Futura",
    fontface = "bold",
  ) +
  scale_colour_manual(values = c("black", "grey50")) +
  theme_leo() +
  theme(
    panel.background = element_rect(fill = "white", colour = NA),
    legend.position = "none",
    plot.background = element_rect(fill = "white", colour = NA),
    axis.title = element_blank(),
    axis.text = element_blank()
  )

pdf("UPSC.pdf", width = 5, height = 5)
map
dev.off()
```
